# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, you can obtain one at http://mozilla.org/MPL/2.0/.

sudo: false
language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/virtualenv/python2.7.9
    - node_modules
env:
  global:
    - DB=mysql
    - TREEHERDER_DATABASE_NAME='treeherder'
    - TREEHERDER_DATABASE_USER='root'
    - TREEHERDER_DATABASE_PASSWORD=''
    - TREEHERDER_DATABASE_HOST='localhost'
    - TREEHERDER_MEMCACHED='127.0.0.1:11211'
    - TREEHERDER_MEMCACHED_KEY_PREFIX='treeherder'
    - TREEHERDER_RABBITMQ_USER='guest'
    - TREEHERDER_RABBITMQ_PASSWORD='guest'
    - TREEHERDER_RABBITMQ_VHOST='/'
    - TREEHERDER_RABBITMQ_HOST='127.0.0.1'
    - TREEHERDER_RABBITMQ_PORT='5672'
services:
  - rabbitmq
  - memcached
install:
  - npm install
  - ./bin/peep.py install -r requirements/common.txt
  - ./bin/peep.py install -r requirements/dev.txt
before_script:
  - flake8 --show-source
  # Required for Karma tests (http://docs.travis-ci.com/user/gui-and-headless-browsers/)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - python setup.py build_ext --inplace
  - mysql -e 'create database treeherder;'
script:
  - npm test
  - py.test tests/$* --runslow
notifications:
  email:
    on_success: never
    on_failure: always

# Do not run these on the travis server at this time.
# The end to end tests require the service to be running, but travis can't
# start the service for us.  So we would have to have the default point to
# a dedicated dev service instance that is reach-able by travis.  However, we
# require /etc/hosts to have an entry at this point to reach our current dev
# server.  So these tests should be run only locally for now.
# - karma start config/karma-e2e.conf.js --reporters=dots --browsers=Firefox
